### ISSUE TITLE
发起者dealloc时，网络请求没有被cancel

### ISSUE THREAD

**Issue by FelixYin66** [YasinZhou/NetWorkingDemo#1]
在YANetworkingAutoCancelRequests 类中修改 dealloc中的代码，如下：
-(void)dealloc{
    [self.requestEngines enumerateKeysAndObjectsUsingBlock:^(NSNumber * _Nonnull key, YABaseDataEngine * _Nonnull obj, BOOL * _Nonnull stop) {
        [obj cancelRequest];
    }];
    [self.requestEngines removeAllObjects];
    self.requestEngines = nil;
}

**Comment by YasinZhou** [comment]
恩，是的，当时写demo的时候遗漏了这个逻辑

**Comment by YasinZhou** [comment]
谢谢提醒，已经修改
